Repository itpp-labs/pos-addons, pull requests merged in 2020-06, with the labels that each got.

#1175 13.0 pos order note port
  pos_order_note/README.rst
  pos_order_note/__manifest__.py
  pos_order_note/doc/index.rst
  pos_order_note/i18n/de.po
  pos_order_note/i18n/es.po
  pos_order_note/i18n/it.po
  pos_order_note/i18n/pos_order_note.pot
  pos_order_note/i18n/ru.po
  pos_order_note/static/src/js/order_note.js
  pos_order_note/static/src/js/tour.js
  pos_order_note/tests/__init__.py
  pos_order_note/tests/default_test.py
  pos_order_note/tests/test_default.py
  pos_order_note/views/views.xml
  pos_restaurant_base/README.rst
  pos_restaurant_base/__manifest__.py
  pos_restaurant_base/i18n/pos_restaurant_base.pot
Labels: 13.0

#1079 :arrow_up::one::two: pos_partner_deselection
  pos_partner_deselection/README.rst
  pos_partner_deselection/__manifest__.py
  pos_partner_deselection/doc/index.rst
  pos_partner_deselection/static/src/js/test_pos_deselection.js
  pos_partner_deselection/tests/test_partner_deselection.py
  pos_partner_deselection/views/pos_config_view.xml
Labels: 12.0

#1271 :tada::one::two: pos_employee_select
  pos_cashier_select/static/src/js/main.js
  pos_cashier_select/static/src/js/tour.js
  pos_employee_select/README.rst
  pos_employee_select/__init__.py
  pos_employee_select/__manifest__.py
  pos_employee_select/doc/changelog.rst
  pos_employee_select/doc/index.rst
  pos_employee_select/models/__init__.py
  pos_employee_select/models/models.py
  pos_employee_select/static/description/icon.png
  pos_employee_select/static/src/css/styles.css
  pos_employee_select/static/src/js/chrome.js
  pos_employee_select/static/src/js/gui.js
  pos_employee_select/static/src/js/models.js
  pos_employee_select/static/src/js/screens.js
  pos_employee_select/static/src/xml/pos.xml
  pos_employee_select/views/template.xml
  pos_employee_select/views/views.xml
Labels: 12.0, needs review

#1278 :tada::one::one: qcloud_sms (from #1181)
  qcloud_sms/README.rst
  qcloud_sms/__init__.py
  qcloud_sms/__manifest__.py
  qcloud_sms/doc/changelog.rst
  qcloud_sms/doc/index.rst
  qcloud_sms/images/qcloud_sms1.jpg
  qcloud_sms/models/__init__.py
  qcloud_sms/models/ir_config_parameter.py
  qcloud_sms/models/qcloud_sms.py
  qcloud_sms/security/ir.model.access.csv
  qcloud_sms/static/description/icon.png
  qcloud_sms/tests/__init__.py
  qcloud_sms/tests/test_qcloud_sms.py
  qcloud_sms/views/res_config.xml
  requirements.txt
Labels: 11.0, ready to merge
